Class {
	#name : #GtPhlowViewTesterViewContentExceptionFailureResult,
	#superclass : #GtPhlowViewTesterExceptionFailureResult,
	#instVars : [
		'exceptionElements'
	],
	#category : #'GToolkit-Phlow-Examples-Tester'
}

{ #category : #accessing }
GtPhlowViewTesterViewContentExceptionFailureResult >> exceptionElements [
	^ exceptionElements
]

{ #category : #accessing }
GtPhlowViewTesterViewContentExceptionFailureResult >> exceptionElements: aCollection [
	exceptionElements := aCollection
]
