Class {
	#name : #GtPhlowChangeViewAndElementPreparation,
	#superclass : #Object,
	#instVars : [
		'phlowView',
		'element'
	],
	#category : #'GToolkit-Phlow-Updating New'
}

{ #category : #accessing }
GtPhlowChangeViewAndElementPreparation >> element [
	^ element
]

{ #category : #accessing }
GtPhlowChangeViewAndElementPreparation >> element: anObject [
	element := anObject
]

{ #category : #accessing }
GtPhlowChangeViewAndElementPreparation >> phlowView [
	^ phlowView
]

{ #category : #accessing }
GtPhlowChangeViewAndElementPreparation >> phlowView: anObject [
	phlowView := anObject
]
