Class {
	#name : #GtPhlowToolEmptySelectionStateHandler,
	#superclass : #Object,
	#traits : 'TGtPhlowToolSelectionStateHandler',
	#classTraits : 'TGtPhlowToolSelectionStateHandler classTrait',
	#category : #'GToolkit-Phlow-Tool - Selection'
}

{ #category : #actions }
GtPhlowToolEmptySelectionStateHandler >> applySelectionStateTo: aToolElement [
	"Apply a stored selected state to an element.
	
	Do nothing."

	
]

{ #category : #actions }
GtPhlowToolEmptySelectionStateHandler >> storeSelectionStateFrom: aToolElement [
	"Store tool element's selected state.
	
	Do nothing."

	
]
