Class {
	#name : #GtPhlowChangeTitleIconAndLabelWish,
	#superclass : #GtPhlowChangeTitleWish,
	#instVars : [
		'icon',
		'label'
	],
	#category : #'GToolkit-Phlow-Tool - Title'
}

{ #category : #'api - accessing' }
GtPhlowChangeTitleIconAndLabelWish >> icon [
	^ icon
]

{ #category : #'api - accessing' }
GtPhlowChangeTitleIconAndLabelWish >> icon: anObject [
	icon := anObject
]

{ #category : #'api - accessing' }
GtPhlowChangeTitleIconAndLabelWish >> label [
	^ label
]

{ #category : #'api - accessing' }
GtPhlowChangeTitleIconAndLabelWish >> label: anObject [
	label := anObject
]
