Class {
	#name : #GtPhlowChangeBinaryInterestCondition,
	#superclass : #GtPhlowChangeInterestCondition,
	#instVars : [
		'left',
		'right'
	],
	#category : #'GToolkit-Phlow-Updating New'
}

{ #category : #accessing }
GtPhlowChangeBinaryInterestCondition >> left [
	^ left
]

{ #category : #accessing }
GtPhlowChangeBinaryInterestCondition >> left: anObject [
	left := anObject
]

{ #category : #accessing }
GtPhlowChangeBinaryInterestCondition >> right [
	^ right
]

{ #category : #accessing }
GtPhlowChangeBinaryInterestCondition >> right: anObject [
	right := anObject
]
