"
I do not attach any tooltip.


"
Class {
	#name : #GtPhlowTooltipNullBuilder,
	#superclass : #GtPhlowTooltipBuilder,
	#traits : 'TGtUniqueInstance',
	#classTraits : 'TGtUniqueInstance classTrait',
	#category : 'GToolkit-Phlow-Support - Tooltip'
}

{ #category : #building }
GtPhlowTooltipNullBuilder >> applyOn: anElement [
	"ignore"
]

{ #category : #building }
GtPhlowTooltipNullBuilder >> applyOn: anElement hostElement: aTargetElement [
	"ignore"
]
