Class {
	#name : #GtPhlowChangeTabPreparation,
	#superclass : #Object,
	#instVars : [
		'phlowView',
		'tabElement'
	],
	#category : #'GToolkit-Phlow-Updating New'
}

{ #category : #accessing }
GtPhlowChangeTabPreparation >> phlowView [
	^ phlowView
]

{ #category : #accessing }
GtPhlowChangeTabPreparation >> phlowView: anObject [
	phlowView := anObject
]

{ #category : #accessing }
GtPhlowChangeTabPreparation >> tabElement [
	^ tabElement
]

{ #category : #accessing }
GtPhlowChangeTabPreparation >> tabElement: anObject [
	tabElement := anObject
]
