"
I define object's context menu items that can be displayed in an inspector header. 
See:
 {{gtExample:GtPhlowViewWithScripterExamples>>#labelledView_headerContextMenu | noCode | previewHeight=400}}
 
 Try for yourself:
 {{gtExample: GtPhlowViewWithScripterExamples>>#labelledViewElement | noCode | previewShow=#gtLiveFor:}}  
 
 
"
Class {
	#name : #GtPhlowObjectContextMenuTarget,
	#superclass : #GtPhlowActionUniqueTarget,
	#category : #'GToolkit-Phlow-Action Targets'
}
