Class {
	#name : #GtPhlowConcreteDefiningMethodProvider,
	#superclass : #GtPhlowDefiningMethodProvider,
	#instVars : [
		'definingMethod'
	],
	#category : #'GToolkit-Phlow-Collectors'
}

{ #category : #accessing }
GtPhlowConcreteDefiningMethodProvider >> definingMethod [
	^ definingMethod
]

{ #category : #accessing }
GtPhlowConcreteDefiningMethodProvider >> definingMethod: aDefiningMethod [
	definingMethod := aDefiningMethod
]
